version: 2.1
jobs:  
  build_ckan_28:
    working_directory: ~/ckanext-datagovtheme
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=2.8
    steps:
      - checkout
      - run:
          name: where am I
          command: pwd && ls -la
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run-tests.sh

  build_ckan_23:
    working_directory: ~/ckanext-datagovtheme
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=2.3
    steps:
      - checkout
      - run:
          name: where am I
          command: pwd && ls -la
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run-tests-bootstrap2.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_ckan_23
      - build_ckan_28

